---
  tasks:
    - name: Create vector_home dir
      file:
        path: "{{ vector_home }}"
        state: directory
        mode: 0777
      tags: vector
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "{{ vector_url }}"
        dest: "{{ vector_home }}/vector-{{ vector_version }}-1.x86_64.rpm"
      tags: vector
    - name: Install vector packages
      become: true
      ansible.builtin.yum:
        name: "{{ vector_home }}/vector-{{ vector_version }}-1.x86_64.rpm"
      notify: Start Vector service
